kafka:
  topic: test
  bootstrapAddress: localhost:9092
  groupId: fr.esir.jxc

server:
  port: 8099

readApi:
  port: 8080

writeApi:
  port: 8081

userEventsHandler:
  port: 8082

elasticsearch:
  home: /usr/local/opt/elasticsearch@5.6
  cluster:
    host: 127.0.0.1
    port: 9300
    name: jxc-cluster
